<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1' => 'ขั้นตอนที่ 1',
	'LBL_IMPORT_STEP_1_DESCRIPTION' => 'เลือกไฟล์',
	'LBL_IMPORT_SUPPORTED_FILE_TYPES' => '	ได้เฉพาะไฟล์: .CSV, .VCF',
	'LBL_IMPORT_STEP_2' => 'ขั้นตอนที่ 2',
	'LBL_IMPORT_STEP_2_DESCRIPTION' => 'Specify Format',
	'LBL_FILE_TYPE' => 'ประเภทไฟล์',
	'LBL_CHARACTER_ENCODING' => 'รหัสภาษา',
	'LBL_DELIMITER' => 'Delimiter',
	'LBL_HAS_HEADER' => 'มีหัวตาราง',
	'LBL_IMPORT_STEP_3' => 'ขั้นตอนที่ 3',
	'LBL_IMPORT_STEP_3_DESCRIPTION' => 'รายการที่ซ้ำ',
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED' => 'Select this option to enable and set duplicate merge criteria',
	'LBL_SPECIFY_MERGE_TYPE' => 'Select how duplicate records should be handled',
	'LBL_SELECT_MERGE_FIELDS' => 'Select the matching fields to find duplicate records',
	'LBL_AVAILABLE_FIELDS' => 'ฟิลด์ที่ใช้ได้',
	'LBL_SELECTED_FIELDS' => 'Fields to be matched on',
	'LBL_NEXT_BUTTON_LABEL' => 'ต่อไป',
	'LBL_IMPORT_STEP_4' => 'ขั้นตอนที่ 4',
	'LBL_IMPORT_STEP_4_DESCRIPTION' => 'Map the Columns to Module Fields',
	'LBL_FILE_COLUMN_HEADER' => 'หัวตาราง',
	'LBL_ROW_1' => 'แถวที่ 1',
	'LBL_CRM_FIELDS' => 'CRM Fields',
	'LBL_DEFAULT_VALUE' => 'ค่าเริ่มต้น',
	'LBL_SAVE_AS_CUSTOM_MAPPING' => 'Save as Custom Mapping ',
	'LBL_IMPORT_BUTTON_LABEL' => 'นำเข้า',
	'LBL_RESULT' => 'ผลลัพภ์',
	'LBL_TOTAL_RECORDS_IMPORTED' => 'รายการที่สำเร็จ',
	'LBL_NUMBER_OF_RECORDS_CREATED' => 'รายการที่สร้าง',
	'LBL_NUMBER_OF_RECORDS_UPDATED' => 'รายการที่เขียนทับ',
	'LBL_NUMBER_OF_RECORDS_SKIPPED' => 'รายการที่ข้าม',
	'LBL_NUMBER_OF_RECORDS_MERGED' => 'รายการที่รวม', 
	'LBL_TOTAL_RECORDS_FAILED' => 'รายการที่ผิดพลาด',
	'LBL_IMPORT_MORE' => 'นำเข้าอีก',
	'LBL_VIEW_LAST_IMPORTED_RECORDS' => 'รายการที่นำเข้าล่าสุด',
	'LBL_UNDO_LAST_IMPORT' => 'กลับไปรายการนำเข้าล่าสุด',
	'LBL_FINISH_BUTTON_LABEL' => 'เสร็จสิ้น',
	'LBL_UNDO_RESULT' => 'Undo Import Result',
	'LBL_TOTAL_RECORDS' => 'จำนวนรวม',
	'LBL_NUMBER_OF_RECORDS_DELETED' => 'จำนวนที่ลบ',
	'LBL_OK_BUTTON_LABEL' => 'Ok',
	'LBL_IMPORT_SCHEDULED' => 'Import Scheduled',
	'LBL_RUNNING' => 'ทำงาน..',
	'LBL_CANCEL_IMPORT' => 'ยกเลิก',
	'LBL_ERROR' => 'ผิดพลาด',
	'LBL_CLEAR_DATA' => 'ล้างข้อมูล',
	'ERR_UNIMPORTED_RECORDS_EXIST' => 'ไม่สามารถสร้างการนำเข้าได้ โปรดลองใหม่อีกครั้ง.',
	'ERR_IMPORT_INTERRUPTED' => 'ถูกขัดจังหวัด โปรดลองใหม่อีกครั้ง',
	'ERR_FAILED_TO_LOCK_MODULE' => 'Failed to lock the module for import. Re-try again later',
	'LBL_SELECT_SAVED_MAPPING' => 'เลือกที่บันทึกการจับคู่',
	'LBL_IMPORT_ERROR_LARGE_FILE' => 'ผิดพลาดไฟล์ใหญ่เกิน ',
	'LBL_FILE_UPLOAD_FAILED' => 'การอัฟโหลดผิดพลาด',
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE' => 'Import Change Upload Size',
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE' => 'โฟลเดอร์ไม่สามารถเขียนทับได้',
	'LBL_IMPORT_FILE_COPY_FAILED' => 'Import File copy failed',
	'LBL_INVALID_FILE' => 'ไฟล์ผิดพลาด',
	'LBL_NO_ROWS_FOUND' => 'หาไม่เจอ',
	'LBL_SCHEDULED_IMPORT_DETAILS' => 'Your import has been scheduled and will start within 15 minutes. You will receive an email after import is completed.  <br> <br>
										Please make sure that the Outgoing server and your email address is configured to receive email notification',
	'LBL_DETAILS' => 'รายละเอียด',
	'skipped' => 'รายการที่ข้าม',
	'failed' => 'รายการที่ผิดพลาด',
	
);
