<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

$languageStrings = Array (
	'MailManager' => 'ตู้จดหมาย',
	
	// General translations
	'LBL_Folders'         => 'โฟลเดอร์',
	'LBL_Newer'           => 'ใหม่',
	'LBL_Older'           => 'เก่า',
	'LBL_No_Mails_Found'  => 'ไม่มีจดหมาย.',
	'LBL_Go_Back'         => 'กลับ',
	'LBL_Reply_All'       => 'ตอบกลับทั้งหมด',
	'LBL_Reply'           => 'ตอบกลับ',
	'LBL_Mark_As_Unread'  => 'กำหนดเป็นไม่อ่าน',
	'LBL_Previous'        => 'ก่อนหน้า',
	'LBL_Next'            => 'ต่อไป',
	'LBL_RELATED_RECORDS' => 'Related Records',
	'LBL_Mailbox'         => 'ตู้จดหมาย',
	'LBL_Outbox'          => 'CRM Outbox',
	'LBL_Like'            => 'ชอบ',
	'LBL_Mail_Server'     => 'Mail Server Name or IP',
	'LBL_Refresh'         => 'รีเฟรช',
	'LBL_Cancel'          => 'ยกเลิก',
	'LBL_Send'            => 'ส่ง',
	'LBL_Compose'         => 'สร้าง',
	'LBL_Forward'         => 'ส่งต่อ',
	'LBL_Remove'          => 'ลบ',
	'LBL_Associate'       => 'Associate',
	'LBL_Create_Contact'  => 'สร้างผู้ติดต่อ',
	'LBL_No_Matching_Record_Found' => 'ไม่มีรายการ.',
	'LBL_ACTIONS'         => 'แอคชั่น',
	'LBL_Search'          => 'ค้นหา',
	'LBL_Delete'            =>  'ลบ',
	
	'LBL_Username'             => 'ชื่อผู้ใช้งาน',
	'LBL_Your_Mailbox_Account' => 'ตู้จดหมาย',
	'LBL_Password'             => 'รหัสผ่าน',
	'LBL_Account_Password'     => 'บัญชีรหัสผ่าน',
	'LBL_Protocol'    => 'Protocol',
	'LBL_Imap2'       => 'IMAP2',
	'LBL_Imap4'       => 'IMAP4',
	'LBL_SSL_Options' => 'SSL Options',
	'LBL_No_TLS'      => 'No TLS',
	'LBL_TLS'         => 'TLS',
	'LBL_SSL'         => 'SSL',
	'LBL_Certificate_Validations' => 'Certificate Validations',
	'LBL_Validate_Cert'           => 'Validate cert',
	'LBL_Do_Not_Validate_Cert'    => 'Do not validate cert',
	'LBL_SELECT_ACCOUNT_TYPE'     => 'Select Organization Type',
	
	'LBL_FROM'        => 'จาก',
	'LBL_TO'          => 'ถึง',
	'LBL_CC'          => 'CC',
	'LBL_BCC'         => 'BCC',
	'LBL_Date'        => 'วันที่',
	'LBL_Attachments' => 'ไฟล์แนบ',
	'LBL_EMAIL_TEMPLATES_LIST'=>'อีเมลล์เทมเพลต',
	'LBL_SELECT_EMAIL_TEMPLATE'=>'Select Email template',
	'LBL_ATTACHMENTS'  =>'ไฟล์แนบ:',
	'LBL_SELECT_DOCUMENTS'=>'เลือกเอกสาร',
	'LBL_IN' =>'ใน',
	'LBL_FIND'=>'หา',
	'LBL_SAVE_NOW'=>'บันทึก',
	'LBL_Drafts'=>'ร่าง',
 	'LBL_NO_EMAILS_SELECTED' => 'ไม่ได้เลือก.',
	'LBL_SUBJECT'	=>	'หัวเรื่อง',
	'LBL_WRITE_ACCESS_FOR'	=>'Write access for',
	'LBL_READ_ACCESS_FOR'	=>'Read access for',
	'LBL_MODULE_DENIED' => 'module denied!',
	'LBL_REFRESH_TIME'=>'Refresh Time',
	'LBL_NONE' => 'None',
	'LBL_5_MIN' => '5 นาที',
	'LBL_10_MIN' => '10 นาที',
	'LBL_MOVE_TO'=>'Move To...',
    'LBL_MAILMANAGER_ADD_Contacts' => 'เพิ่มผู้ติดต่อ',
    'LBL_MAILMANAGER_ADD_Accounts' => 'เพิ่มลูกค้า',
    'LBL_MAILMANAGER_ADD_Leads' => 'เพิ่มผู้คาดหวัง',
    'LBL_MAILMANAGER_ADD_Calendar' => 'เพิ่มสิ่งที่ต้องทำ',
    'LBL_MAILMANAGER_ADD_HelpDesk' => 'เพิ่มการแจ้งปัญหา',
    'LBL_MAILMANAGER_ADD_Emails' => 'Attach Email',
    'LBL_MAILMANAGER_ADD_ModComments' => 'เพิ่มคอมเม้นท์',
    'LBL_ADD' => 'เพิ่ม',
	'JSLBL_Body_Cannot_Be_Empty' => 'เนื้อหาห้ามว่าง',
	'LBL_ALLMAILS' => 'ทุกอีเมลล์',
	'LBL_TO_CONTACTS' => 'ถึงผู้ติดต่อ',
	'LBL_TO_ACCOUNTS' => 'ถึงลูกค้า',
	'LBL_TO_LEADS' => 'ถึงผู้คาดหวัง',
	'LBL_TO_USERS' => 'ถึงผู้ใช้งาน',
	'LBL_SENT_MAILS' => 'ส่งจดหมาย',
	'LBL_Print' => 'พิมพ์',
	
	'LBL_SAVE_BUTTON_LABEL' => 'บันทึก',
	'LBL_CANCEL_BUTTON_LABEL' => 'ยกเลิก',
	'LBL_CREATE_MAILBOX' => 'สร้างตู้จดหมาย',
	'LBL_WRITE_YOUR_COMMENT_HERE' => 'เพิ่งคอมเม้นที่นี่ ...'
);

$jsLanguageStrings = Array (
	'MailManager' => 'Mail Manager',
	
	// Translations for JS (please use the prefix JSLBL in key)
	'JSLBL_Loading_Please_Wait'  => 'กำลังโหลด โปรดรอ',
	'JSLBL_Loading'              => 'โหลด....',
	'JSLBL_Settings'             => 'ตั้งค่า',
	'JSLBL_Opening'              => 'กำลังเปิด',
	'JSLBL_Deleting'              => 'กำลังลบ',  
	'JSLBL_Updating'             => 'กำลังอัฟเดท',
	'JSLBL_Associating'          => 'Associating',
	'JSLBL_Saving_And_Verifying' => 'กำลังตรวจสอบและบันทึก',
	'JSLBL_Failed_To_Open_Mail'  => 'Failed to open the mail',
	'JSLBL_Finding_Relation'     => 'Finding relation',
	'JSLBL_Find_Relation_Now'    => 'Find relation now',
	'JSLBL_Searching'            => 'กำลังค้นหา',
	'JSLBL_Searching_Please_Wait'=> 'กำลังค้นหา รอสักครู่',
	'JSLBL_Sending'              => 'กำลังส่ง',
	'JSLBL_Replied'              => 'ตอบกลับ',
	'JSLBL_Failed_To_Send_Mail'  => 'ผิดพลาดไม่สามารถส่งได้',
	'JSLBL_Recepient_Cannot_Be_Empty' => 'ผู้รับไม่สามารถเป็นค่าว่างได้',
	'JSLBL_Subject_Cannot_Be_Empty'     => 'หัวเรื่องไม่สามารถเป็นค่าว่างได้',
	'JSLBL_Removing'                  => 'กำลังลบ',
	'JSLBL_Choose_Server_Type'        => 'เลือกประเภทผู้ให้บริการ',
	'JSLBL_Other'                     => 'อื่นๆ',
	'JSLBL_Gmail'                     => 'Gmail',
	'JSLBL_Fastmail'                  => 'Fastmail',
	'JSLBL_Search_For_Email'          => 'ค้นอีเมลล์',
	'JSLBL_Nothing_Found'             => 'ไม่เจอ',
	'JSLBL_Delete_Confirm'            =>'Do you want to delete the Emails permanently?',
	'JSLBL_Delete_Mails_Confirm'      =>'ต้องการจะลบหรือ ?',
	'JSLBL_Receipents_Warning_Message'=>'กรุณาเลือกผู้รับ',
	'JSLBL_NO_MATCH'				  => 'ไมเจอ',
	'JSLBL_Saving'					=> 'กำลังบันทึก',
	'JSLBL_Failed_To_Save_Mail'		=>	'ไม่สามารถบันทึกได้',
	'JSLBL_ATTACHMENT_NOT_DELETED'	=>	'ไม่สามารถลบได้',
	'JSLBL_UPLOAD_CANCEL'	=> 'ยกเลิก',
	'JSLBL_UPLOAD_DROPFILES'=>'Drop files here to upload',
	'JSLBL_UPLOAD_FILE'=>'อัฟโหลด',
	'JSLBL_UPLOAD_DELETE'=>'[x]',
	'JSLBL_UPLOAD_FAILED'=>'ผิดพลาด',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'=>'ไฟล์อัฟโหลดเต็ม!!',
	'JSLBL_MAIL_SENT'=>'ส่งอีเมลล์',
	'JSLBL_EMAIL_FORMAT_INCORRECT'=>'Please provide proper email address',
	'JSLBL_Saving'=>'กำลังบันทึก',
	'JSLBL_SaveWith_EmptySubject'=>'Save with subject empty?',
	'JSLBL_Delete'            =>  'ลบ',
	'JSLBL_Drafts'=>'ร่าง',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'=>'รหัส่ผ่านห้ามว่าง',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'=>'ชื่อโฮสต์ห้ามว่าง',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'=>'ชื่อผู้ใช้ห้ามว่าง',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'=>'ชื่อลูกค้าห้ามว่าง',
	'JSLBL_FROM'=>'จาก:',
	'JSLBL_DATE'=>'วันที่: ',
	'JSLBL_SUBJECT'=>'หัวเรื่อง: ',
	'JSLBL_TO'=>'ถึง: ',
	'JSLBL_CC'=>'Cc: ',
	'JSLBL_FORWARD_MESSAGE_TEXT'=>'---------- Forwarded message ----------',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'=>'Please select at least one mail',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'=>'Please select at least one record',
	'JSLBL_MAIL_MOVED'=>'Mail(s) moved',
	'JSLBL_MOVING'=>'Moving Mail(s)',
	'JSLBL_LOADING_FOLDERS' => 'โหลด โฟลเดอร์..',
	'JSLBL_ADD_COMMENT'=>'เพิ่มคอมเม้นต์',
    'JSLBL_Yahoo'=>'Yahoo',
    'JSLBL_CANNOT_ADD_EMPTY_COMMENT' => 'คอมเม้นต์ห้ามว่าง',
    'JSLBL_NO_EMAILS_SELECTED' => 'ไม่ได้เลือก.',
    'JSLBL_ENTER_SOME_VALUE' => 'พิมพ์ข้อความในการค้นหา',
    'JSLBL_DRAFT_MAIL_SAVED'=>'อีเมลล์ได้บันทึกฉบับร่างไว้',
);

// Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);