<?php
/*+***********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 *************************************************************************************/
$languageStrings = array(

	// Footer
	'APPTITLE' => 'vtiger CRM',
	'POWEREDBY'=> 'Powered by vtiger CRM | ภาษาไทย โดย : <a href="http://www.crm.in.th" target="_blank">www.crm.in.th</a>',
	'LBL_READ_LICENSE' => 'อ่านไลเซนส์',
	'LBL_PRIVACY_POLICY' => 'ข้อกำหนด',

	// Common Actions
	'LBL_SELECT_ALL' => 'เลือกทั้งหมด',
	'LBL_SELECT_TO_LOAD_LIST' => 'Select to Load List',
	'LBL_CREATING_NEW' => 'กำลังจะสร้าง',
	'LBL_EDITING' => 'กำลังแก้ไข',
	'LBL_SAVE' => 'บันทึก',
	'LBL_CANCEL' => 'ยกเลิก',
	'LBL_BACK' => 'กลับ',
	'LBL_IMPORT' => 'นำเข้า',
	'LBL_EXPORT' => 'ส่งออก',
	'LBL_FIND_DUPLICATES' => 'หารายการซ้ำ',
	'LBL_MORE' => 'มีอีก',
	'LBL_ACTIONS' => 'กระทำ',
    'LBL_ADD' => 'เพิ่ม',
	'LBL_EDIT' => 'แก้ไข',
	'LBL_DELETE' => 'ลบ',
	'LBL_SETTINGS'=> 'ตั้งค่า',
	'LBL_ADD_COMMENT' => 'เพิ่มคอมเม้นต์',
	'LBL_EDIT_FIELDS' => 'แก้ไขฟิลด์',
	'LBL_EDIT_WORKFLOWS' => 'แก้ไขเวริคโฟว์',
	'LBL_EDIT_PICKLIST_VALUES' => 'แก้ไขค่า Picklist',
	'LBL_EDIT_MAILSCANNER' => 'Mail Converter',
	'LBL_RECORD_DELETE' => 'The record you are trying to view has been deleted.',
	'LBL_RECORD_NOT_FOUND' => 'Record you are trying to access is not found',
	'LBL_EDIT_REASON' => 'Edit reason',

	//'LBL_EDIT_CURRENT_FILTER' => 'Edit Current Filter',
	//'LBL_DELETE_CURRENT_FILTER' => 'Delete Current Filter',
	'LBL_SELECT' => 'เลือก',
	'LBL_CLEAR' => 'เคลีย',
	'LBL_YES' => 'ใช่',
	'LBL_NO' => 'ไม่',
	'LBL_SHOW_COMPLETE_DETAILS' => 'รายการเสร็จ',
    'LBL_MASS_EDITING' => 'กำลังแก้ไขหลายรายการ',
	'LBL_DESELECT_ALL_RECORDS' => 'ไม่เลือกทุกรายการ',
	'LBL_QUICK_CREATE' => 'สร้างแบบด่วน',
	'LBL_SEND_EMAIL' => 'ส่งอีเมลล์',
	//SEND EMAIL translations
	'LBL_ALL_EMAILS' => 'All email accounts',
	'LBL_MUTIPLE_EMAIL_SELECT_ONE' => 'Please select one of the options below',
	//SEND EMAIL translations
	'LBL_GO_TO_FULL_FORM' => 'กรอกแบบเต็มรูปแบบ',
	'LBL_SEND_SMS' => 'ส่ง SMS',
	'LBL_FOUND' => 'เจอ',
	'LBL_CLICK_ADD' => 'คลิกเพิ่ม',
	'LBL_ADD_MORE_FIELDS' => 'เพิ่มฟิลด์อีก',
	'LBL_ADD_NOTE' => 'เพิ่มเอกสาร',
	'LBL_CREATE_NEW' => 'สร้างใหม่',
    'LBL_ADD_EVENT' => 'เพิ่มอีเว้นต์',
    'LBL_ADD_TASK' => 'เพิ่มงาน',
	'LBL_MARKETING_AND_SALES' => 'MARKETING & SALES',
	'LBL_TOOLS_HEADER' => 'เครื่องมือ',
	'LBL_SUPPORT' => 'สนับสนุน',
	'LBL_INVENTORY' => 'INVENTORY',
	'LBL_ANALYTICS' => 'วิเคราะห์',
	'LBL_HOME' => 'หน้าหลัก',

	// Common Link Labels
	'LBL_LAST_VIEWED_RECORDS' => 'รายการดูล่าสุด',
	'LBL_DASHBOARD' => 'ดาสบอร์ด',
	'LBL_USER_SETTINGS' => 'ตั้งค่าผู้ใช้งาน',
	'LBL_MY_PREFERENCES' => 'ตั้งค่าส่วนตัว',
	'LBL_SIGN_OUT' => 'ออกจากระบบ',
	'LBL_HELP' => 'ช่วยเหลือ',
	'LBL_DOCUMENTATION' => 'เอกสาร',
	'LBL_VIDEO_TUTORIAL' => 'วิดีโอสอน',
	'LBL_FEEDBACK' => 'Feedback',
	'LBL_CRM_SETTINGS' => 'ตั้งค่า CRM',
	'LBL_ON_DEMAND_ADMIN' => 'เพิ่มลบแก้ไขผู้ใช้งาน',
	'LBL_ANNOUNCEMENT' => 'ประกาศ',
	'LBL_CALENDAR' => 'ปฏิทิน',
	'LBL_POST' => 'โพส',
	'LBL_GUIDER' => 'Guider',
	'LBL_DISPLAY_TYPE' => 'ประเภทการแสดงผล',
	'LBL_DISPLAY_WIDETYPE' => 'Wide',
	'LBL_DISPLAY_MEDIUMTYPE' => 'Medium',
	'LBL_DISPLAY_NARROWTYPE' => 'Narrow',
	'LBL_TAG_THIS_RECORD' => 'Tag this Record',
	'LBL_PAGE' => 'หน้า',
	'LBL_LISTVIEW_PAGE_JUMP' => 'Page Jump',
	'LBL_PROFILE_PASSWORD' => 'Profile / Password',

	// Common Fields
	'LBL_USER' => 'ผู้ใช้งาน',
	'LBL_GROUP' => 'กลุ่ม',
	'Last Modified By' => 'แก้ไขล่าสุดโดย',
	'Created Time' => 'เวลาสร้าง',
	'Modified Time' => 'เวลาแก้ไข',
	'Description' => 'รายละเอียด',
	'Assigned To'=>'ผู้รับผิดชอบ',

	//Loading Labels
	'LBL_LOADING' => 'โหลด.....',
	'LBL_LOADING_WIDGET' => 'โหลดวิดเจด',
	'LBL_LOADING_LISTVIEW_CONTENTS'	=> 'กำลังโหลด...',

	// Detail View
	'LBL_UPDATES' => 'กำลังอัฟเดท',
	'LBL_SHOW_FULL_DETAILS' => 'แสดงแบบเต็ม',
	'LBL_SUMMARY_DETAILS' => 'รายละเอียดโดยรวม',
	'LBL_ADD_NEW_COMMENT' =>'เพิ่มคอมเม้นต์ใหม่',
	'LBL_NO_UPDATES' => 'ไม่มีอัฟเดท',
	'LBL_ACTIVITIES' => 'กิจกรรม',
	'LBL_NO_PENDING_ACTIVITIES' => 'ไม่มีกิจกรรมค้าง',
	'LBL_SUMMARY' => 'ภาพรวม',
	'LBL_DETAILS' => 'รายละเอียด',

	// Popup window
	'LBL_SEARCH_FOR' => 'ค้นหา',
	'LBL_IN' => 'ใน',
	'LBL_TYPE_SEARCH' => 'ค้นหา',
	'LBL_SEARCH_BUTTON' => 'ปุ่มค้นหา',
	'LBL_ADVANCE_SEARCH' => 'แบบละเอียด',
	'LBL_LOADING_PLEASE_WAIT' => 'กำลังโหลด...',
	'LBL_PLEASE_SELECT_MODULE' => 'โปรดเลือกโมดูล',

	//DropDown Category
	'LBL_USERS' => 'ผู้ใช้งาน',
	'LBL_GROUPS' => 'กลุ่ม',

	//EditView Form Links
	'LBL_FULL_FORM' => 'แบบเต็ม',
	'LBL_SIMPLE_FORM' => 'แบบรวดเร็ว',

	//Recent Comments
	'LBL_ADD_YOUR_COMMENT_HERE' => 'เพิ่มคอมเม้นต์ที่นี่..',
	'LBL_REASON_FOR_CHANGING_COMMENT' => 'Reason for changing comment',
	'LBL_REPLY' => 'ตอบกลับ',
	'LBL_VIEW_THREAD' => 'View Thread',
	'LBL_NO_COMMENTS' => 'No comments',
	'LBL_REPLIES' => 'ตอบกลับ',

	//Translation for all modules
	'Accounts' => 'ลูกค้า',
	'Assets' => 'ทรัพย์สิน',
	'Calendar' => 'ปฏิทิน',
	'Campaigns' => 'แคมเปญ',
	'Contacts' => 'ผู้ติดต่อ',
	'Documents' => 'เอกสาร',
	'Leads' => 'ผู้คาดหวัง',
	'ModComments' => 'คอมเม้นต์',
	'Potentials' => 'งานขาย',
	'PriceBooks' => 'ใบกำหนดราคา',
	'Products' => 'สินค้า',
	'Project' => 'โปรเจค',
	'ProjectMilestone' => 'โปรเจคไมล์สโตน',
	'ProjectTask' => 'ทาสก์งานโปรเจค',
	'ServiceContracts' => 'สัญญาการบริการ',
	'Services' => 'บริการ',
	'Vendors' => 'ผู้ขาย',
	'Rss' => 'RSS',
	'Quotes'=>'ใบเสนอราคา',
	'PurchaseOrder'=>'ใบสั่งซื้อ',
	'SalesOrder'=>'ใบสั่งขาย',
	'Invoice'=>'ใบแจ้งหนี้',
	'MailManager' => 'ตู้จดหมาย',
	'Activities' => 'กิจกรรม',


	//Basic String Translation
	'LBL_ADD_RECORD' => 'เพิ่มรายการ',
	'LBL_RECENTLY_MODIFIED' => 'แก้ไขล่าสุด',
	'LBL_RECORDS_LIST' => 'Records List',
	'LBL_RECORD_SUMMARY' => 'ภาพรวมโมดูล',
	'LBL_RECORD_SUMMARY' => 'รายละเอียดโมดูล',
	'LBL_ACCESS_DENIED_FOR' => 'ไม่มีสิทธิ์',
	'LBL_GO_BACK' => 'กลับ',
	'LBL_NO_DATA_AVAILABLE' => 'ไม่มีข้อมูล',

	// Global Search
	'LBL_GLOBAL_SEARCH' => 'พิมพ์ข้อความแล้วกด Enter',
	'LBL_ALL_RECORDS' => 'ทุกรายการ',
	'LBL_NO_RECORDS_FOUND' => 'ไม่เจอ',

	//Filters & Advance Filter
	'LBL_AND' => 'และ',
	'LBL_OR' => 'หรือ',
	'LBL_NONE' => 'ว่าง',
	'LBL_APPROVE' => 'อนุมัติ',
	'LBL_DENY' => 'ไม่อนุมัติ',
	'LBL_EQUALS' => 'เท่ากับ',
	'LBL_NOT_EQUAL_TO' => 'ไม่เท่ากับ',
	'LBL_STARTS_WITH' => 'เริ่มที่',
	'LBL_ENDS_WITH' => 'สิ้นสุดที่',
	'LBL_CONTAINS' => 'ค้นหาใน',
	'LBL_DOES_NOT_CONTAIN' => 'ไม่มีในคำนั้น',
	'LBL_LESS_THAN' => 'น้อยกว่า',
	'LBL_GREATER_THAN' => 'มากกว่า',
	'LBL_LESS_THAN_OR_EQUAL' => 'น้อยกว่าหรือเท่ากับ',
	'LBL_GREATER_OR_EQUAL' => 'มากกว่าหรือเท่ากับ',
	'LBL_BEFORE' => 'ก่อน',
	'LBL_AFTER' => 'หลัง',
	'LBL_BETWEEN' => 'ระหว่าง',
	'LBL_SEARCH' => 'ค้นหา',
	'LBL_SEARCH_IN' => 'ค้นหา',
	'LBL_ADD_CONDITION' => 'เพิ่มเงื่อนไข',
	'LBL_ADD_GROUP' => 'เพิ่มกลุ่มเงื่อนไข',
	'LBL_FILTER_CONDITIONS' => 'กรองเงื่อนไข',
	'LBL_ALL_CONDITIONS' => 'ทุกเงื่อนไข',
	'LBL_ALL_CONDITIONS_DESC' => 'ทุกเงื่อนไขต้องเจอ',
	'LBL_ANY_CONDITIONS' => 'เงื่อนไขอื่นๆ',
	'LBL_ANY_CONDITIONS_DESC' => 'At least one of the conditions must be met',
	'LBL_SELECT_FIELD' => 'เลือกฟิลด์',
	'LBL_SELECT_MODULE' => 'เลือกโมดูล',
	'LBL_CREATE_NEW_FILTER' => 'สร้างตัวกรอง',
	'All' => 'ทั้งหมด',
	'Others' => 'อื่นๆ',
	'Pending' => 'ค้าง',
	'Public' => 'ทั่วไป',

	//Advance Search
	'LBL_SAVE_FILTER' => 'บันทึกตัวกรอง',
	'LBL_SAVE_MODIFY_FILTER' => 'แก้ไขตัวกรอง',
	'LBL_SEARCH_RESULTS' => 'ค้นหาผลลัพท์',
	'LBL_SAVE_AS_FILTER' => 'บันทึกเป็นตัวกรอง',

	//Exception String Translation
	'LBL_NOT_ACCESSIBLE' => 'ไม่มีสิทธิ์',

	//Line Items
	'LBL_ITEM_DETAILS'=> 'รายละเอียดรายการ',
	'LBL_CURRENCY' => 'สกุลเงิน',
	'LBL_TAX_MODE' => 'ภาษี',
	'LBL_INDIVIDUAL' => 'แยก',
	'LBL_GROUP' => 'กลุ่ม',
	'LBL_TOOLS' => 'เครื่องมือ',
	'LBL_ITEM_NAME' => 'ชื่อรายการ',
	'LBL_QTY_IN_STOCK' => 'สต๊อก',
	'LBL_QTY' => 'Quantity',
	'LBL_LIST_PRICE' => 'List Price',
	'LBL_TOTAL' => 'รวม',
	'LBL_NET_PRICE' => 'Net Price',
	'LBL_DISCOUNT' => 'ส่วนลด',
	'LBL_TOTAL_AFTER_DISCOUNT' => 'ราคารวมหลังส่วนลด',
	'LBL_TAX' => 'ภาษี',
	'LBL_ADD_PRODUCT' => 'เพิ่มสินค้า',
	'LBL_ADD_SERVICE' => 'เพิ่มบริการ',
	'LBL_ITEMS_TOTAL' => 'รายการรวม',
	'LBL_SHIPPING_AND_HANDLING_CHARGES' => 'Shipping & Handling Charges',
	'LBL_PRE_TAX_TOTAL' => 'ราคาก่อนภาษี',
	'LBL_TAX_FOR_SHIPPING_AND_HANDLING' => 'Taxes For Shipping and Handling',
	'LBL_SET_SHIPPING_AND_HANDLING_TAXES_FOR' => 'Set S&H Taxes For',
	'LBL_ADJUSTMENT' => 'Adjustment',
	'LBL_DEDUCT' => 'Deduct',
	'LBL_GRAND_TOTAL' => 'Grand Total',
	'LBL_ZERO_DISCOUNT' => 'Zero Discount',
	'LBL_OF_PRICE' => 'ราคา',
	'LBL_DIRECT_PRICE_REDUCTION' => 'Direct Price Reduction',
	'LBL_SET_DISCOUNT_FOR' => 'Set Discount For',
	'LBL_STOCK_NOT_ENOUGH' => 'Not enough stock',
	'LBL_MAX_QTY_SELECT' => 'Maximum value is',
	'LBL_DRAG' => 'Drag',
	'LBL_TOTAL_TAX_AMOUNT' => 'Total Tax Amount',
	'LBL_DIRECT_AMOUNT_DISCOUNT' => 'Direct Amount Discount',
	'LBL_FINAL_DISCOUNT_AMOUNT' => 'Final Discount Amount',
	'LBL_MORE_CURRENCIES' => 'more currencies',
	'LBL_SET_TAX_FOR' => 'Set Tax for',
	'LBL_GROUP_TAX' => 'Group Tax',
	'LBL_BILLING_ADDRESS_FROM' => 'Copy Billing Address from',
	'LBL_SHIPPING_ADDRESS_FROM' => 'Copy Shipping Address from',
	'LBL_COPY_SHIPPING_ADDRESS' => 'Shipping Address',
	'LBL_COPY_BILLING_ADDRESS' => 'Billing Address',

	//DetailView Actions
	'LBL_CREATE' => 'สร้าง',
	'LBL_GENERATE' => 'สร้าง',
    'LBL_DUPLICATE' => 'ทำซ็ำ',
	'Add Note' => 'เพิ่มเอกสาร',

	//Dashboard String
	'LBL_ADD_WIDGET' => 'เพิ่มวิดเจด',
	'LBL_COMMENTS' => 'คอมเม้นต์',
	'LBL_REFRESH' => 'รีเฟรช',
	'LBL_CLOSE' => 'ปิด',
	'LBL_ALL' => 'ทั้งหมด',
	'LBL_UPDATED' => 'อัฟเดท',
	'LBL_FROM' => 'จาก',
	'LBL_TO' => 'ถึง',
	'LBL_to' => 'ถึง',
	'LBL_ON' => 'on',
	'LBL_OF' => 'of',
	'LBL_BY' => 'โดย',
	'LBL_ADDED' => 'เพิ่ม',
	'LBL_FOR' => 'สำหรับ',
	'LBL_CREATED' => 'สร้าง',
	'LBL_DELETED' => 'ลบ',
	'LBL_RESTORED' => 'กู้คืน',
	'LBL_COMMENTED' => 'คอมเม้นต์',
	'LBL_REMOVED' => 'ลบ',
	'LBL_REMOVE' => 'ลบ',
	'LBL_AT' => 'ที่',
	'LBL_MINE' => 'Mine',
	'History' => 'ประวัติ',
	'Upcoming Tasks' => 'งานที่จะมาถึง',
	'LBL_YEAR' => 'ปี',
	'LBL_YEARS' => 'ปี',
	'LBL_MONTH' => 'เดือน',
	'LBL_MONTHS' => 'เดือน',
	'LBL_DAY' => 'วัน',
	'LBL_DAYS' => 'วัน',
	'LBL_HOUR' => 'ชั่วโมง',
	'LBL_HOURS' => 'ชั่วโมง',
	'LBL_MINUTE' => 'นาที',
	'LBL_MINUTES' => 'นาที',
	'LBL_SECOND' => 'วินาที',
	'LBL_SECONDS' => 'วินาที',
	'LBL_JUSTNOW' => 'ตอนนี้',
	'LBL_CUSTOM_INFORMATION' => 'Custom Information',
	'LBL_NO_RECENT_UPDATES' => 'No recent updates',
	'LBL_NO_DATA' => 'ไม่มีข้อมูล',
	'LBL_PERMISSION_DENIED' => 'ไม่มีสิทธิ์',
	'LBL_HANDLER_NOT_FOUND' => 'Handler not found',
	'LBL_FILTER' => 'ตัวกรอง',
	'LBL_DUE' => 'due in',
	'LBL_DAYS' => 'วัน',
	'LBL_COMPLETED' => 'เสร็จ',
	'LBL_AGO' => 'ผ่านมา',
	'LBL_CHANGED' => 'เปลี่ยน',
	'Single_Users' => 'ผู้ใช้',
	'LBL_MATCHED_THIS_CRITERIA'=> 'matched this criteria',
	'LBL_NO_SCHEDULED_ACTIVITIES' => 'No scheduled activities',
	'LBL_NO_OVERDUE_ACTIVITIES' => 'No overdue activities',
	'LBL_NO_UPDATES_OR_COMMENTS' => 'No updates or comments',
	'LBL_MINI_LIST' => 'Mini List',
	'LBL_NOTEPAD' => 'สมุดบันทึก',
	'LBL_NOTEPAD_NAME' => 'ชื่อสมุดบันทึก',
	'LBL_NOTEPAD_CONTENT' => 'รายละเอียด',
	'LBL_LAST_SAVED_ON' => 'Last saved on',
	'Mini List' => 'Mini List',
	'Notebook' => 'สมุดบันทึก',
	'LBL_RESULT_FOR_THE_TAG' => 'Results for the tag',

	// Basic Strings- custom view
	'LBL_VIEW_NAME' => 'ชื่อมุมมอง',
	'LBL_CREATE_VIEW' => 'สร้างมุมมอง',
	'LBL_BASIC_DETAILS' => 'รายเอียดเบื้องต้น',
	'LBL_CHOOSE_COLUMNS' => 'Choose Columns and Order',
	'LBL_MAX_NUMBER_FILTER_COLUMNS' => 'Max 12',
	'LBL_FILTER_ON_DATE' => 'Filter on date',
	'LBL_CHOOSE_FILTER_CONDITIONS' => 'Choose filter Conditions',
	'LBL_ADD_CONDITION' => 'เพิ่มเงื่อนไข',
	'LBL_SET_AS_DEFAULT' => 'ตั้งเป็นค่าเริ่มต้น',
	'LBL_LIST_IN_METRICS' => 'List in Metrics',
	'LBL_SET_AS_PUBLIC' => ' ตั้งเป็นสาธารณะ',
	'LBL_AND' => 'และ',
	'LBL_OR' => 'หรือ',
	'LBL_ADD_MORE_COLUMNS' => 'เพิ่มคอลัมม์',
	'LBL_ADD_GROUP' => 'เพิ่มกลุ่ม',


	//DateFilter Conditions
	'LBL_CUSTOM' => 'กำหนดเอง',
	'LBL_PREVIOUS_FY' => 'ปีที่แล้ว',
	'LBL_CURRENT_FY' => 'ปีนี้',
	'LBL_NEXT_FY' => 'ปีหน้า',
	'LBL_PREVIOUS_FQ' => 'Previous FQ',
	'LBL_CURRENT_FQ' => 'Current FQ',
	'LBL_NEXT_FQ' => 'Next FQ',
	'LBL_YESTERDAY' => 'เมื่อวาน',
	'LBL_TODAY' => 'วันนี้',
	'LBL_TOMORROW' => 'วันนี้พรุ่ง',
	'LBL_LAST_WEEK' => 'อาทิตย์ที่แล้ว',
	'LBL_CURRENT_WEEK' => 'อาทิตย์นี้',
	'LBL_NEXT_WEEK' => 'อาทิตย์หน้า',
	'LBL_LAST_MONTH' => 'เดือนที่แล้ว',
	'LBL_CURRENT_MONTH' => 'เดือนนี้',
	'LBL_NEXT_MONTH' => 'เดือนหน้า',
	'LBL_LAST_7_DAYS' => '7 วันที่ผ่าน',
	'LBL_LAST_30_DAYS' => '30 วันที่ผ่าน',
	'LBL_LAST_60_DAYS' => '60 วันที่ผ่าน',
	'LBL_LAST_90_DAYS' => '90 วันที่ผ่าน',
	'LBL_LAST_120_DAYS' => '120 วันที่ผ่าน',
	'LBL_NEXT_30_DAYS' => '30 วันถัดไป',
	'LBL_NEXT_60_DAYS' => '60 วันถัดไป',
	'LBL_NEXT_90_DAYS' => '90 วันถัดไป',
	'LBL_NEXT_120_DAYS' => '120 วันถัดไป',

	//advanced Filter Options
	'LBL_NONE' => 'NONE',
	'LBL_EQUALS' => 'เท่ากับ',
	'LBL_NOT_EQUAL_TO' => 'ไม่เท่ากับ',
	'LBL_STARTS_WITH' => 'เริ่มที่',
	'LBL_ENDS_WITH' => 'สิ้นสุดที่',
	'LBL_CONTAINS' => 'ค้นหาในคำ',
	'LBL_DOES_NOT_CONTAIN' => 'ไม่มีในคำ',
	'LBL_LESS_THAN' => 'น้อยกว่า',
	'LBL_GREATER_THAN' => 'มากกว่า',
	'LBL_LESS_THAN_OR_EQUAL' => 'น้อยกว่าหรือเท่ากับ',
	'LBL_GREATER_OR_EQUAL' => 'มากกว่าหรือเท่ากับ',
	'LBL_BEFORE' => 'ก่อน',
	'LBL_AFTER' => 'หลัง',
	'LBL_BETWEEN' => 'ระหว่าง',
	'LBL_IS_EMPTY'=> 'ว่าง',

	//Detail view summary widgets
	'LBL_OWNER' => 'เจ้าของ',
	'LBL_CREATED_ON' => 'สร้างเมื่อ',
	'LBL_MODIFIED_ON' => 'แก้ไขเมื่อ',
	'LBL_MODIFIED' => 'แก้ไข',
	'LBL_COMMENTED' => 'คอมเม้นต์',

    //calender set-reminder
    'LBL_BEFORE_EVENT' => ' ก่อนอีเว้นท์',

	//Dashboard widgets
	'History' => 'ประวัติ',
	'Upcoming Activities' => 'กิจกรรมใกล้',
	'Overdue Activities' => 'กิจกรรมที่ผ่านมา',
	'Funnel' => 'Funnel',
	'Potentials by Stage' => 'งานขายตามสถานะ',
	'Pipelined Amount' => 'Sales Pipeline',
	'Total Revenue' => 'รวมยอดขาย',
	'Top Potentials' => 'งานขายเด่น',
	'Forecast' => 'การประมาณการ',
	'Leads Created' => 'สร้างผู้คาดหวัง',
	'Leads by Status' => 'ผู้ที่คาดตามสถานะ',
	'Leads by Source' => 'ผู้ที่คาดตามที่มา',
	'Leads by Industry' => 'ผู้ที่คาดตามอุตสาหกรรม',
	'Tickets by Status' => 'ผู้ที่คาดตามสถานะ',
	'Open Tickets' => 'เพิ่มการแจ้งปัญหา',
	'Funnel Amount' => 'Total Amount by Sales stage',

	//Exports strings
	'LBL_EXPORT_ALL_DATA' => 'นำออกทุกรายการ',
	'LBL_EXPORT_DATA_IN_CURRENT_PAGE' => 'นำออกเฉพาะหน้าปัจจุบัน',
	'LBL_EXPORT_SELECTED_RECORDS' => 'นำออกเฉพาะรายการที่เลือก',
	'LBL_EXPORT_RECORDS' => 'นำออกรายการ',
	'LBL_NO_RECORD_SELECTED' => 'ไม่ได้เลือก.',
	'LBL_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'ไม่สามารถลบวิดเจดได้',
	'LBL_CUSTOM_VIEW_NAME_DUPLICATES_EXIST' => 'filter already exists',

	'LBL_ADD_MANAGE_MODULES' => 'เพิ่มและจัดการโมดูล',
	'LBL_CUSTOMIZE_MAIN_MENU' => 'จัดการเมนูหลัก',

	// Added Common Keys for all modules
	'Account Name' => 'ชื่อลูกค้า',
	'Add Comment' => 'เพิ่มคอมเม้นต์',
	'Adjustment' => 'Adjustment',
	'Annual Revenue' => 'Annual Revenue',
	'Apparel'=>'Apparel',
	'Banking'=>'Banking',
	'Billing Address' => 'ที่อยู่ในการจัดส่งบิล',
	'Billing City' => 'อำเภอจัดส่งบิล',
	'Billing Code' => 'รหัสไปรษณีย์จัดส่งบิล',
	'Billing Country' => 'ประเทศจัดส่งบิล',
	'Billing Po Box' => 'เลขที่จัดส่งบิล',
	'Billing State' => 'จังหวัดจัดส่งบิล',
	'Biotechnology'=>'Biotechnology',

	//for SO PO and Quotes
	'FedEx'=>'FedEx',
	'UPS'=>'UPS',
	'USPS'=>'USPS',
	'DHL'=>'DHL',
	'BlueDart'=>'BlueDart',
	'Carrier' => 'Carrier',
	'Category'=>'Category',
	'Chemicals'=>'Chemicals',
	'City' => 'City',

	'Cold Call'=>'Cold Call',
	'Existing Customer'=>'Existing Customer',
	'Self Generated'=>'Self Generated',
	'Employee'=>'Employee',
	'Partner'=>'Partner',
	'Public Relations'=>'Public Relations',
	'Direct Mail'=>'Direct Mail',
	'Conference'=>'Conference',
	'Trade Show'=>'Trade Show',
	'Web Site'=>'Web Site',
	'Word of mouth'=>'Word of mouth',
	'Other'=>'Other',

	//for leads and accounts
	'--None--'=>'--None--',
	'Acquired'=>'Acquired',
	'Active'=>'Active',
	'Market Failed'=>'Market Failed',
	'Project Cancelled'=>'Project Cancelled',
	'Shutdown'=>'Shutdown',
	'Apparel'=>'Apparel',
	'Banking'=>'Banking',
	'Biotechnology'=>'Biotechnology',
	'Chemicals'=>'Chemicals',
	'Communications'=>'Communications',
	'Construction'=>'Construction',
	'Consulting'=>'Consulting',
	'Education'=>'Education',
	'Electronics'=>'Electronics',
	'Energy'=>'Energy',
	'Engineering'=>'Engineering',
	'Entertainment'=>'Entertainment',
	'Environmental'=>'Environmental',
	'Finance'=>'Finance',
	'Food & Beverage'=>'Food & Beverage',
	'Government'=>'Government',
	'Healthcare'=>'Healthcare',
	'Hospitality'=>'Hospitality',
	'Insurance'=>'Insurance',
	'Machinery'=>'Machinery',
	'Manufacturing'=>'Manufacturing',
	'Media'=>'Media',
	'Not For Profit'=>'Not For Profit',
	'Recreation'=>'Recreation',
	'Retail'=>'Retail',
	'Shipping'=>'Shipping',
	'Technology'=>'Technology',
	'Telecommunications'=>'Telecommunications',
	'Transportation'=>'Transportation',
	'Utilities'=>'Utilities',

	'Contact Name' => 'Contact Name',
	'Conversion Rate' => 'Conversion Rate',

	'Shipping Address' => 'ที่อยู่จัดส่ง',
	'Shipping City' => 'อำเภอจัดส่ง',
	'Shipping State' => 'จังหวัดจัดส่ง',
	'Shipping Code' => 'รหัสจัดส่ง',
	'Shipping Country' => 'ประเทศจัดส่ง',
	'Shipping Po Box' => 'เลชที่จัดส่ง',
	'Country' => 'ประเทศ',
	'Description' => 'รายละเอียด',

	'Created'=>'สร้าง',
	'Approved'=>'อนุมัติ',
	'Delivered'=>'ไม่อนุมัติ',
	'Cancelled'=>'ยกเลิก',

	'Currency' => 'สกุลเงิน',
	'LBL_BASE_CURRENCY' => 'Base Currency',

	'Discount Percent' => 'ส่วนลด %',
	'Discount Amount' => 'ส่วนลด',
	'Item Discount Amount' => 'Item Discount Amount',
	'Item Discount Percent' => 'Item Discount Percent',

	'Due Date' => 'ช่วงเวลา',
	'Due Date & Time' => 'Due Date & Time',
	'Email' => 'อีเมลล์',
	'Secondary Email' => 'อีเมลล์สำรอง',
	'Other Email' => 'อีเมลล์อื่นๆ',
	'Email Opt Out' => 'Email Opt Out',

	'Expected Close Date' => 'วันที่คาดว่าจะปิด',

	'Fax' => 'โทรสาร',

	'Last Name' => 'ชื่อสกุล',
	'First Name' => 'ชื่อจริง',

	'High' => 'สูง',
	'Low' => 'ต่ำ',

	'In Progress' => 'กำลังดำเนินการ',


	'Subject' => 'หัวเรื่อง',
	'Shipping Address'=>'ที่อยู่จัดส่ง',
	'Shipping Po Box'=>'เลขที่ในการจัดส่ง',
	'Shipping City'=>'อำเภอจัดส่ง',
	'Shipping State'=>'จังหวัดจัดส่ง',
	'Shipping Code'=>'Shipping Postal Code',
	'Shipping Country'=>'Shipping Country',
	'Terms & Conditions' => 'Terms & Conditions',
	'Item Name' => 'ชื่อรายการ',
	'Quantity' => 'Quantity',
	'List Price' => 'List Price',
	'Item Comment' => 'Item Comment',
	'Tax1' => 'ภาษี 1',
	'Tax2' => 'ภาษี 2',
	'Tax3' => 'ภาษี 3',
	'Excise Duty' => 'Excise Duty',
	'Total' => 'Total',
	'Sub Total' => 'Sub Total',
	'Tax Type' => 'Tax Type',
	'S&H Amount' => 'S&H Amount',
	'Status' => 'Status',
	'Vendor Name'=>'Vendor Name',

	'LBL_ADDRESS_INFORMATION' => 'รายละเอียดที่อยู่',
	'LBL_DESCRIPTION_INFORMATION' => 'รายละเอียด',
	'LBL_TERMS_INFORMATION' => 'เงื่อนไขการบริการ',
	'LBL_PRICING_INFORMATION' => 'ข้อมูลราคา',
	'LBL_RELATED_PRODUCTS' => 'ข้อมูลสินค้า',
	'LBL_REMINDER_INFORMATION' => 'รายละเอียดแจ้งเตือน',

	'LBL_FOLDER_SAVED' => 'บันทึกโฟลเดอร์',
	'LBL_FOLDER_EXISTS' => 'โฟลเดอร์ถูกสร้างแล้ว',
	'LBL_FOLDER_DELETED' => 'โฟลเดอร์ถูกลบแล้ว',

	'Lead Source' => 'ที่มาของผู้คาดหวัง',
	'Mobile' => 'เบอร์โทรศัพท์มือถือ',

	'Notify Owner' => 'แจ้งเตือนเจ้าของ',
	'Other Phone' => 'เบอร์โทรสำรอง',
	'Phone' => 'เบอร์โทรศัพท์',

	'State' =>  'จังหวัด',
	'Po Box' => 'เลขที่',
	'Postal Code' => 'รหัสไปรษณีย์',

	'Potential Name' => 'ชื่องานขาย',
	'Priority'=>'ความสำคัญ',

	'Product Name' => 'ชื่อสินค้า',
	'Rating' => 'เรทติ้ง',

	'Related To'=>'เป็นของ',
	'Type' => 'ประเภท',

	'Reviewed'=>'Reviewed',
	'Salutation' => 'Salutation',
	'Street' => 'ถนน',
	'Support Start Date' => 'วันที่เริ่ม Support',
	'Support Expiry Date' => 'วันที่สิ้นสุด Support',
	'Sales Start Date'=>'วันที่เริ่มขาย',
	'Sales End Date'=>'วันที่สิ้นสุดการขาย',

	//Dashboard list of widgets translation
	'Open Tickets' => 'เปิดการแจ้งปัญหา',
	'LBL_SELECT_STATUS' => 'เลือกสถานะ',
	'LBL_BLANK' => '-ว่าง-',

	//PageTitle translations
	'LBL_VTIGER_CRM_HONEST_OPEN_SOURCE' => 'vtiger CRM honest Open Source',

	//Translations used in inventory modules for sopy address
	'SINGLE_Accounts' => 'ลูกค้า',
	'SINGLE_Contacts' => 'ผู้ติดต่อ',

	//Weekdays in 3 letters translations
	'LBL_Sun' => 'อ.',
	'LBL_Mon' => 'จ.',
	'LBL_Tue' => 'อ.',
	'LBL_Wed' => 'พ.',
	'LBL_Thu' => 'พฤ.',
	'LBL_Fri' => 'ศ.',
	'LBL_Sat' => 'ส.',

	//Months in 3 letters translations
	'LBL_Jan' => 'ม.ค.',
	'LBL_Feb' => 'ก.พ.',
	'LBL_Mar' => 'มี.ค.',
	'LBL_Apr' => 'เม.ย.',
	'LBL_May' => 'พ.ค.',
	'LBL_Jun' => 'มิ.ย.',
	'LBL_Jul' => 'ก.ค.',
	'LBL_Aug' => 'ส.ค.',
	'LBL_Sep' => 'ก.ย.',
	'LBL_Oct' => 'ต.ค.',
	'LBL_Nov' => 'พ.ย.',
	'LBL_Dec' => 'ธ.ค.',

	'LBL_CALENDAR_SETTINGS' => 'ตั้งค่าปฏิทิน',

	//Translations used in inventory modules for address
	'SINGLE_Accounts' => 'ลูกค้า',
	'SINGLE_Contacts' => 'ผู้ติดต่อ',
	'HelpDesk' => 'แจ้่งปัญหา',
	'LBL_TAG_CLOUD' => 'แท็กคลาว',

	'LBL_NO_RECORDS' => 'ไม่มีรายการ',
	'LBL_NO_RELATED' => 'No Related',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE' => 'Only the first 100 results of all modules are shown below. For module specific results, please select respective module and search',
	'LBL_GLOBAL_SEARCH_MAX_MESSAGE_FOR_MODULE' => 'Only the first 100 results are shown below. Please do Advanced Search if you are not satisfied with the result',

	// used in reports detail view
	'LBL_ACTION' => 'การกระทำ',
	'LBL_NOTE' => 'บันทึก',
	'LBL_SELECT_OPTION' => 'Select an Option',

	//Module Manager
	'LBL_TOOLTIP' => 'จัดการคำอธิบาย',
	'LBL_MODULE_SEQUENCE_NUMBERING' => 'Module Sequence Numbering',
	'LBL_CUSTOM_FIELD_MAPPING' => 'Custom Field Mapping',
	'LBL_WEBFORMS' => 'เว็บฟอร์ม',

	//Compose Email Strings
	'SINGLE_Emails' => 'อีเมลล์',
	'Emails' => 'อีเมลล์',
	'LBL_SELECT_EMAIL_IDS' => 'เลือกที่อยู่อีเมลล์',
	'LBL_SUBJECT' => 'หัวเรื่อง',
	'LBL_ATTACHMENT' => 'ไฟล์แนบ',
	'LBL_BROWSE_CRM' => 'Browse CRM',
	'LBL_SEND' => 'ส่ง',
	'LBL_SAVE_AS_DRAFT' => 'บันทึกร่าง',
	'LBL_GO_TO_PREVIEW' => 'แสดงตัวอย่าง',
	'LBL_SELECT_EMAIL_TEMPLATE' => 'เลือกอีเมลล์เทมเพลต',
	'LBL_COMPOSE_EMAIL' => 'สร้างอีเมลล์',
 	'LBL_CC' => 'Cc',
   	'LBL_BCC' => 'Bcc',
   	'LBL_ADD_CC' => 'Add Cc',
   	'LBL_ADD_BCC' => 'Add Bcc',
	'LBL_MAX_UPLOAD_SIZE' => 'Maximum upload size is',
	'LBL_EXCEEDED' => 'Exceeded',
	'LBL_OPERATION_NOT_PERMITTED' => 'Operation not permitted',
    'LBL_MERGE' => 'Merge',
	'LBL_MERGING_CRITERIA_SELECTION' => 'Merging Criteria Selection',
	'LBL_AVAILABLE_FIELDS' => 'Available Fields',
	'LBL_MERGE_RECORDS_DESCRIPTION' => 'The primary record will be retained after the merge. You can select the column to retain the values.
										The other record will be deleted but the related information will be merged.',
	'LBL_MERGE_RECORDS_IN' => 'Merge Records In',
	'LBL_FIELDS' => 'Fields',
	'LBL_RECORD' => 'Record',
	'LBL_NO_DUPLICATED_FOUND' => 'No duplicates found',
	'LBL_MERGE_SELECT' => 'Merge Select',

	//sbproducts translation
	'LBL_BACK_TO_PRODUCTS' => 'Back to products',

	//Translations used for Export to Pdf
	'Valid Date' => 'Valid Date',
	'Phone: ' => 'Phone: ',
	'Issued Date' => 'Issued Date',
	'Shipping & Handling Charges' => 'Shipping & Handling Charges',
	'Shipping & Handling Tax:' => 'Shipping & Handling Tax:',
	'Discount'=>'Discount',
	'Net Total' => 'Net Total',
	'Product Code'=>'Product Code',
	'Customer Name'=>'Customer Name',
	'Price'=>'Price',
	'Tax:' => 'Tax:',
	'Contact Name' => 'Contact Name',
	'Grand Total:' => 'Grand Total:',
	'Fax: ' => 'Fax: ',
	'Website: ' => 'Website: ',
	'Tax' => 'Tax',
	'LBL_ALPHABETS' => 'A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z',

	//Realted tab strings
	'Service Contracts' => 'Service Contracts',
	'Projects' => 'Projects',
	'Sales Order' => 'ใบสั่งขาย',
	'Purchase Order' => 'ใบสั่งซื้อ',
	'List and Campaigns' => 'List and Campaigns',
	'Project Tasks' => 'Project Tasks',
	'Project Milestones' => 'Project Milestones',

	'Labels Editor' => 'แก้ไข Label',
	'LBL_IGNORE_EMPTY_VALUES' =>'Ignore empty values',

	//Related tabs of Products
	'Product Bundles' => 'Product Bundles',
	'Parent Product' => 'Parent Product',

	'LBL_MANAGE_USERS' => 'Manage Users',
	'LBL_TRANSFER_OWNERSHIP' => 'เปลี่ยนผู้ดูแล',
	'LBL_SELECT_RELATED_MODULES' => 'Select Related Modules',
	'LBL_ASSIGNED_TO' => 'ผู้รับผิดชอบ',

	//Report Detail View
	'LBL_VIEW_DETAILS' => 'ดูรายละเอียด',
	//Comments Field Labels for Workflow
	'Comment' => 'คอมเม้นต์',
	'Last Comment' => 'คอมเม้นต์ล่าสุด',
	'Last 5 Comments' => '5 คอมเม้นต์ล่าสุด',
	'All Comments' => 'ทุกคอมเม้นต์',
);

$jsLanguageStrings = array(
	'JS_EMAIL_SERVER_CONFIGURATION' => 'Please configure your outgoing server settings from the settings page',
	'JS_SMS_SERVER_CONFIGURATION' => 'Please configure your SMS notifier from the SMS notifier settings page',
	'JS_PLEASE_SELECT_ONE_RECORD' => 'Please select at least one record',

	//Validation Error Message
	'JS_PLEASE_ENTER_VALID_EMAIL_ADDRESS' => 'Please enter a valid email address',
	'JS_CONTAINS_ILLEGAL_CHARACTERS' => 'contains illegal characters',
	'JS_PHONE_NUMBER_LENGTH_EXCEEDED' => 'phone number length exceeded limit',
	'JS_ACCEPT_POSITIVE_NUMBER' => 'Accepts only positive numbers',
	'JS_VALUE_SHOULD_BE_GREATER_THAN_ZERO' => 'value should be greater than zero',
	'JS_NUMBER_SHOULD_BE_LESS_THAN_32' => 'Number should be less than 32',
	'JS_PLEASE_ENTER_VALID_DATE' => 'ระบุวันที่ให้ถูกต้อง',
	'JS_PLEASE_ENTER_VALID_TIME' => 'ระบุเวลาให้ถูกต้อง',
	'JS_INVALID_PAGE_NUMBER' => 'กรอกหน้าผิด',


	'INVALID_NUMBER_OF' => 'Invalid number of',
	'INVALID_NUMBER' => 'รูปแบบตัวเลขผิด',
	'JS_LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE' => 'Are you sure that you want to delete?',

	'OVERWRITE_EXISTING_MSG1' => 'Overwrite the existing address with the selected ',
	'OVERWRITE_EXISTING_MSG2' => 'รายละเอียดที่อยู่?',
	'SINGLE_Accounts' => 'ลูกค้า',
	'SINGLE_Contacts' => 'ผู้ติดต่อ',

	'LBL_DELETE_CONFIRMATION' => 'Are you sure you want to delete?', // This is added as duplicate as we need to show different message for different modules. Ex:Accounts has different message
	'LBL_MASS_DELETE_CONFIRMATION' => 'Are you sure you want to delete the selected Records?',
	'JS_LBL_SAVE' => 'บันทึก',
	'JS_LBL_CANCEL' => 'ยกเลิก',
	'JS_DUPLICTAE_CREATION_CONFIRMATION' => 'Organization Name already Exists.Do you want to create a duplicate record?',

	'SHOULD_BE_LESS_THAN_TODAY' => 'Must occur before today',
	'JS_PLEASE_SELECT_ATLEAST_ONE_OPTION' => 'Please select at least one option',
	'JS_SELECT_MODULE' => 'กรุณาเลือกโมดูล',
	'JS_PLEASE_SELECT_ATLEAST_ONE_MANDATORY_FIELD' => 'Please select at least one Mandatory Field',
	'JS_SELECT_MODULE' => 'กรุณาเลือกโมดูล',
	'JS_PLEASE_ENTER_INTEGER_VALUE' => 'กรอกตัวเลข',
	'JS_PLEASE_ENTER_DECIMAL_VALUE' => 'Please enter decimal value',

	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'กรุณากรอกน้อยกว่าวันปัจจุบัน',
	'JS_SHOULD_BE_GREATER_THAN_CURRENT_DATE' => 'should be greater than Current Date',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'should be greater than or equal to',
    'JS_SHOULD_BE_LESS_THAN_OR_EQUAL_TO' => 'should be less than or equal to',
	'JS_PERCENTAGE_VALUE_SHOULD_BE_LESS_THAN_100' => 'Percentage value should be less than 100',
	'JS_ACCEPT_ONLY_NUMBER' => 'Accepts only numbers',
	'JS_THIS_FILE_HAS_ALREADY_BEEN_SELECTED' => 'This File has already been selected',
	'JS_MAX_FILE_UPLOAD_EXCEEDS' => 'max file Upload exceeds',
	'JS_THIS_DOCUMENT_HAS_ALREADY_BEEN_SELECTED' => 'This Document has already been attached',
	'JS_SHOULD_BE_GREATER_THAN_OR_EQUAL_TO' => 'Should be greater than or equal to',


	//Roles
	'JS_FAILED_TO_SAVE' => 'ผิดพลาด',

	//Import Translations
	'JS_IMPORT_FILE_CAN_NOT_BE_EMPTY' => 'Import File cannot be Empty',
	'JS_PLEASE_SELECT_ONE_FIELD_FOR_MERGE' => 'Select at least one field for merge criteria',
	'JS_MAP_NAME_CAN_NOT_BE_EMPTY' => 'Map Name cannot be empty',
	'JS_MAP_NAME_ALREADY_EXISTS' => 'Map Name already exists',
	'JS_SELECT_FILE_EXTENSION' => 'Please select a file with the following extension:',
	'JS_UPLOADED_FILE_SIZE_SHOULD_BE_LESS_THAN' => 'Upload file size should be less than',
	'JS_UPLOADED_FILE_SIZE_EXCEEDS' => 'Uploaded file size exceeds',
	'JS_PLEASE_SPLIT_FILE_AND_IMPORT_AGAIN' => 'Please split the file into smaller files and import again.',
	'JS_FIELD_MAPPED_MORE_THAN_ONCE' => 'Field mapped more than once',
	'JS_MAP_MANDATORY_FIELDS' => 'Please map mandatory fields',
	'JS_PLEASE_ENTER_SOME_VALUE' => 'Please enter some value to search',

	//Select2 elements validation message
	'JS_YOU_CAN_SELECT_ONLY'=> 'You can select only',
	'JS_ITEMS' => 'items',

	'JS_LBL_PERMISSION' => 'Permissions',
	'JS_CHECK_FILE_INTEGRITY' => 'Check File Integrity',
	'JS_DUPLICATE_RECORD' => 'Duplicate Record',

	//advance filter checkbox type condition values
	'JS_IS_ENABLED' => 'is enabled',
	'JS_IS_DISABLED' => 'is disabled',

	'JS_PLEASE_ENTER_SOME_TEXT_FOR_COMMENT' => 'Please enter some text for comment',
	'JS_LBL_COMMENT_VALUE_CANT_BE_EMPTY' => 'Comment value cannot be empty',
	'JS_REQUIRED_FIELD' => '* This field is required',
	'JS_CAN_NOT_REMOVE_DEFAULT_WIDGET' => 'Cannot remove Default Widget',
	'JS_SHOULD_BE_LESS_THAN_CURRENT_DATE' => 'should be less than Current Date',
	'JS_NO_CREATE_OR_NOT_QUICK_CREATE_ENABLED' => 'No create permissions or not enabled for quick create',

	//Image Action
	'LBL_IMAGE_DELETED_SUCCESSFULLY' => 'Image Deleted Successfully',
	'LBL_IMAGE_NOT_DELETED' => 'Image Not Deleted',
	'LBL_YES' => 'ใช่',
	'LBL_NO' => 'ไม่',
	'AM' => 'AM',
	'PM' => 'PM',
 	'JS_ERROR' => 'ผิดพลาด',
	'JS_INFORMATION' => 'ข้อมูล',
	'JS_DO_NOT_HAVE_AN_EMAIL_ID' => 'does not have an email address',
	'NONE_OF_THE_FIELD_VALUES_ARE_CHANGED_IN_MASS_EDIT' => 'None of the field values are changed in Mass Edit',

	//Notification messages for inventory module
	'JS_PLEASE_SELECT_AN_ACCOUNT_TO_COPY_ADDRESS' => 'Please select an Organization to copy address',
	'JS_PLEASE_SELECT_AN_CONTACT_TO_COPY_ADDRESS' => 'Please select a Contact to copy address',
	'JS_SELECTED_ACCOUNT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Organization does not contain address to copy',
	'JS_SELECTED_CONTACT_DOES_NOT_HAVE_AN_ADDRESS' => 'Selected Contact does not contain address to copy',
	'JS_PLEASE_ENTER_PRIMARY_EMAIL_VALUE_TO_ENABLE_PORTAL_USER' => 'Please enter Primary email address to enable portal user',
	'JS_PRIMARY_EMAIL_FIELD_DOES_NOT_EXISTS' => 'Primary email field does not exist to enable portal user',

	//Tag Cloud validation messages
	'JS_PLEASE_ENTER_A_TAG' => 'Please enter a tag',
	'JS_TAG_NAME_ALREADY_EXIST' => 'Tag name already exist',
	'JS_MAX_TAG_LENGTH_EXCEEDS' => 'Tag length exceeds max size',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',
	'JS_NO_RECORDS_RELATED_TO_THIS_FILTER' => 'No Records Related to this Filter',

	// Calendar Reminder popup
	'JS_START_DATE_TIME' => 'Start Date & Time',
	'JS_END_DATE_TIME' => 'End Date & Time',
	'JS_POSTPONE' => 'Postpone',
	'JS_MESSAGE' => 'Message',

	'JS_NO_VIEW_PERMISSION_AFTER_SAVE'=> 'You will not have permissions to view this record after save. Would you like to continue?',

	//Settings page translations
	'JS_SUCCESSFULLY_PINNED' => 'Shortcut added successfully',
	'JS_SUCCESSFULLY_UNPINNED' => 'Shortcut removed successfully',
	'JS_SHORTCUT_ALREADY_ADDED' => 'This shortcut is already added',
	'JS_MESSAGE' => 'ข้อความ',

	//Module Manager
	'JS_MODULE_ENABLED' => 'เปิดโมดูล',
	'JS_MODULE_DISABLED' => 'ปิดโมดูล',

	//Crom tasks
	'JS_VALUE_SHOULD_NOT_BE_LESS_THAN' => 'Frequency of any cron job configured should not be less than',
	'JS_MINUTES' => 'mins',

	//PickList
	'JS_ITEM_RENAMED_SUCCESSFULLY' => 'เปลี่ยนชื่อสำเร็จ',
	'JS_ITEM_ADDED_SUCCESSFULLY' => 'เพิ่มรายการสำเร็จ',
	'JS_NO_ITEM_SELECTED' => 'ไม่มีรายการให้เลือก',
	'JS_MORE_THAN_ONE_ITEM_SELECTED' => 'ให้เลือกมากกว่า 1 รายการ',
	'JS_ITEMS_DELETED_SUCCESSFULLY' => 'ลบสำเร็จ',
	'JS_DUPLIACATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_SELECT_RECORDS_TO_MERGE_FROM_SAME_GROUP' => 'You have to select the records in the same groups for merging',
	'JS_SELECT_ATLEAST_TWO_RECORD_FOR_MERGING' => 'Select at least two records for merging',
	'JS_ALLOWED_TO_SELECT_MAX_OF_THREE_RECORDS' => 'You are allowed to select a maximum of three records',
	//Notification message for dashboard widget delete
	'JS_ARE_YOU_SURE_TO_DELETE_WIDGET' => 'คุณต้องการจะลบวิดเจดหรือไม่?',
	'JS_DUPLICATE_ENTRIES_FOUND_FOR_THE_VALUE' => 'Duplicate entries found for the value',
	'JS_TOTAL_RECORDS' => 'รวมรายการ',
	'JS_PAGE_NOT_EXIST' => 'Page not exist',
	'JS_YOU_ARE_IN_PAGE_NUMBER' => 'You are in page number',

	//More currencies message
	'JS_PLEASE_ENABLE_BASE_CURRENCY_FOR_PRODUCT' => 'Please enable base currency for product',
	'JS_PLEASE_SELECT_BASE_CURRENCY_FOR_PRODUCT' => 'Please select base currency for product',

	//Delete Records message
	'JS_RECORDS_ARE_GETTING_DELETED' => 'Records are getting deleted',
	'JS_RECORD_GETTING_DELETED' => 'รายการถูกลบ',
	'JS_NO_RESULTS_FOUND' => 'ไม่มีรายการ',

	'JS_RECORDS TRANSFERRED SUCCESSFULLY' => 'Records ownership has been tranferred successfully',

	'JS_USER_EXISTS' => 'ผุ้ใช้งานนี้มีแล้ว',
	'JS_REENTER_PASSWORDS' => 'กรอกรหัสผ่านอีกครั้ง',
);
